Update and rename deneme.yml to xtreammakerr2sistemi.yml

diff --git a/.github/workflows/xtreammakerr2sistemi.yml b/.github/workflows/xtreammakerr2sistemi.yml
--- a/.github/workflows/xtreammakerr2sistemi.yml
+++ b/.github/workflows/xtreammakerr2sistemi.yml
@@ -1,7 +1,11 @@
-name: r2 upload try
+name: XTREAM MAKER R2
 
 on:
   workflow_dispatch:
+  workflow_run:
+    workflows: ["M3U MAKER"]
+    types:
+      - completed
 
 env:
   GH_TOKEN: ${{ secrets.GH_TOKEN }}
@@ -18,6 +22,23 @@ env:
 
 
 jobs:
+
+  notify_start:
+    name: 🔔 Telegram Start Notify
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Send Telegram start message
+        env:
+          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
+          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+        run: |
+          MESSAGE="🔔 Xtream workflow başladı!"
+
+          curl -s -o /dev/null -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
+            -d chat_id="$TELEGRAM_CHAT_ID" \
+            -d text="$MESSAGE"
+            
   push-m3u-to-root:
     runs-on: ubuntu-latest
 #    needs: notify_start
@@ -141,9 +162,7 @@ jobs:
           aws s3 cp xtream/series_full.m3u s3://iptv/series_full.m3u \
             --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
             --content-type text/plain
-
-
-
+            
   run-xtream-json:
     runs-on: ubuntu-latest
     needs: run-xtream-m3u
@@ -296,3 +315,21 @@ jobs:
           aws s3 cp series_standard_updated.json s3://iptv/series_standard_updated.json \
             --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
             --content-type "application/json; charset=utf-8"
+
+      - name: Xtream Full Cache Clear
+        run: |
+          echo "🚀 Clearing Full Xtream cache..."
+          curl -X GET "$XTREAM_CACHE_URL" || echo "⚠️ Cache clear request failed"
+
+      - name: Xtream Premium Cache Clear
+        run: |
+          echo "🚀 Clearing Premium Xtream cache..."
+          curl -X GET "$XTREAM_PRE_CACHE_URL" || echo "⚠️ Cache clear request failed"
+         
+      - name: Telegram Success Notification
+        if: success()
+        run: |
+          MESSAGE="✅ Xtream dosyası başarıyla güncellendi!"
+          curl -s -o /dev/null -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
+            -d chat_id="$TELEGRAM_CHAT_ID" \
+            -d text="$MESSAGE"
